[package]
name = "markdwon" # 多分crate名にハイフン仕えない(?)ドキュメントテストのときエラーが出たので
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
