[package]
name = "regex"
version = "0.1.0"
edition = "2021"


[dependencies]
dirs = "4.0.0"
rustyline = "10.0"
nix = "0.25"
signal-hook = "0.3.14"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false
